[usb]
vendor_id = 0x2E8A
product_id = 0x000A
manufacturer = "shawn.dev"
product = "Sweep"
serial_number = "1"

[split]
# Pretty stable at 5_000_000 so this gives us plenty of buffer.
bit_rate = 500_000

[keyboard]
layers = ["Alpha", "Symbol", "Number", "Function"]

[keys.left.pin_7] # top pinky
id = "W"
tap.Alpha = "w"
[keys.left.pin_26] # top ring
id = "L"
tap.Alpha = "l"
[keys.left.pin_27] # top middle
id = "Y"
tap.Alpha = "y"
[keys.left.pin_28] # top index
id = "P"
tap.Alpha = "p"
[keys.left.pin_29] # top center
id = "B"
tap.Alpha = "b"

[keys.left.pin_22] # home pinky
id = "C"
tap.Alpha = "c"
[keys.left.pin_20] # home ring
id = "R"
tap.Alpha = "r"
[keys.left.pin_23] # home middle
id = "S"
tap.Alpha = "s"
[keys.left.pin_21] # home index
id = "T"
tap.Alpha = "t"
[keys.left.pin_0] # home center
id = "G"
tap.Alpha = "g"

[keys.left.pin_2] # bottom pinky
id = "Q"
tap.Alpha = "q"
[keys.left.pin_3] # bottom ring
id = "J"
tap.Alpha = "j"
[keys.left.pin_4] # bottom middle
id = "V"
tap.Alpha = "v"
[keys.left.pin_5] # bottom index
id = "D"
tap.Alpha = "d"
[keys.left.pin_6] # bottom center
id = "K"
tap.Alpha = "k"

[keys.left.pin_8] # thumb left
id = "Dup"
tap.Alpha = "Dup"
[keys.left.pin_9] # thumb right
id = "Backspace"
tap.Alpha = "Backspace"

[keys.right.pin_29] # top center
id = "Z"
tap.Alpha = "z"
[keys.right.pin_28] # top index
id = "F"
tap.Alpha = "f"
[keys.right.pin_27] # top middle
id = "O"
tap.Alpha = "o"
[keys.right.pin_26] # top ring
id = "U"
tap.Alpha = "u"
[keys.right.pin_7] # top pinky
id = "'"
tap.Alpha = "'"

[keys.right.pin_0] # home center
id = "M"
tap.Alpha = "m"
[keys.right.pin_21] # home index
id = "N"
tap.Alpha = "n"
[keys.right.pin_23] # home middle
id = "E"
tap.Alpha = "e"
[keys.right.pin_20] # home ring
id = "I"
tap.Alpha = "i"
[keys.right.pin_22] # home pinky
id = "A"
tap.Alpha = "a"

[keys.right.pin_6] # bottom center
id = "X"
tap.Alpha = "x"
[keys.right.pin_5] # bottom index
id = "H"
tap.Alpha = "h"
[keys.right.pin_4] # bottom middle
id = "."
tap.Alpha = "."
[keys.right.pin_3] # bottom ring
id = ","
tap.Alpha = ","
[keys.right.pin_2] # bottom pinky
id = "Enter"
tap.Alpha = "Enter"

[keys.right.pin_9] # thumb left
id = "Space"
tap.Alpha = "Space"
[keys.right.pin_8] # thumb right
id = "Tab"
tap.Alpha = "Tab"
